development:
  adapter: postgresql
  database: hd_rails_dev
  host: localhost
  username: MontyHackintosh
  encoding: utf8
  pool: 5

test: &test
  adapter: postgresql
  database: hd_rails_test
  host: localhost
  username: MontyHackintosh
  encoding: utf8
  pool: 5

production:
  adapter: postgresql
  database: hd_rails
  encoding: utf8
  pool: 5
cucumber:
  <<: *test
